# Generated by Django 6.0.1 on 2026-01-21 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "match_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("unspecified", "Unspecified"),
                            ("hltv", "HLTV"),
                            ("pandascore", "Pandascore"),
                        ],
                        default="unspecified",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                ("source_match_id", models.CharField(max_length=100)),
                ("match_date", models.DateTimeField()),
                (
                    "best_of",
                    models.CharField(
                        choices=[
                            ("bo1", "Best of 1"),
                            ("bo3", "Best of 3"),
                            ("bo5", "Best of 5"),
                        ],
                        default="bo3",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "matches",
                "db_table": "matches",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "team_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("pandascore_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("hltv_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "tournament_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("organizer", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("prize_pool", models.FloatField()),
                ("online", models.BooleanField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("unspecified", "Unspecified"),
                            ("hltv", "HLTV"),
                            ("pandascore", "Pandascore"),
                        ],
                        default="unspecified",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                ("external_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("scraped_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("team1_score", models.PositiveIntegerField()),
                ("team2_score", models.PositiveIntegerField()),
                ("map_results", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("unspecified", "Unspecified"),
                            ("hltv", "HLTV"),
                            ("pandascore", "PandaScore"),
                        ],
                        default="unspecified",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="core.match",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wins",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "db_table": "results",
            },
        ),
        migrations.AddField(
            model_name="match",
            name="team1_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team_1",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team_2",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="core.tournament",
            ),
        ),
        migrations.CreateModel(
            name="TeamRanking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ranking", models.PositiveIntegerField()),
                ("points", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("hltv_world", "HLTV World Ranking"),
                            ("vrs_world", "VRS World Ranking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("retrieved_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_rankings",
                "ordering": ["-retrieved_at", "ranking"],
                "unique_together": {("team", "source", "retrieved_at")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("source", "source_match_id")},
        ),
    ]
