"""add tables back

Revision ID: 3bfc6a7f5633
Revises: 818cdd04d0ef
Create Date: 2025-12-16 00:49:38.119309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bfc6a7f5633'
down_revision: Union[str, Sequence[str], None] = '818cdd04d0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kd_diff', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kd', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('maps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('team_id', name=op.f('teams_pkey'))
    )
    op.create_table('matches',
    sa.Column('match_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('team1_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('team2_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('match_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tournament_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('winner', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('match_id', name=op.f('matches_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('teams')
    # ### end Alembic commands ###
